FROM frankhinek/keras:tf-cpu

LABEL maintainer="Frank Hinek <frank.hinek@gmail.com>"

# Add the source code files
ADD code /code

# Setting the working directory to the path of the source code
WORKDIR /code
